### ISSUE TITLE
Redirecting a different page to the same domain

### ISSUE THREAD

**Issue by Orisha-Ana** [stephenou/fruitionsite#27]
A few days ago I managed to make my website with fruition. I got the domain on Porkbun and followed the instructions to make my domain redirect the visitor to what I'll call "my notion page 1".

However, I realized I want my visitors to be redirected to my notion page 2 instead.

 I tried remaking my steps with fruition to see if I would have any success and after several trials, I just can't seem to be able to change it...

I suck at programming, my knowledge in this area is less than zero. So how can I change the page my domain is pointing to?

Thank you

**Comment by JECaballeroR** [comment]
Go into your Worker in Cloudflare (Repeat the steps on the  instructions of the page, it's the place where you pasted the code).

Here's the screenshoot from the Fruition page:
![image](https://user-images.githubusercontent.com/62854093/88622134-b7ad0580-d067-11ea-8493-ee202159aa6a.png)


There, in the code, there should be a part that is like:
``
const SLUG_TO_PAGE = {
  '': '1a5f5721gba543tb885538ac7545e360',
};
``
But with a different value on the numers and letters

The numbers and letters are part of the notion url, it's the last part of the url after whatever customization and naming you did in notion. So, following the example, your **notion page 1** link would be something like:

https://www.notion.so/workspacename/name-of-the-page-1a5f5721gba543tb885538ac7545e360

Copy the part with seemingly random numbers and letters of **your Notion page 2** into the Worker in cloudflare, replacing the ones you already have, and  click "Save and Deploy".  

This should make your domain load the notion page 2 instead of notion page 1.

**Comment by Orisha-Ana** [comment]
Thank you very much!! It did work❤️
