### ISSUE TITLE
Options to Cache? 

### ISSUE THREAD

**Issue by darshil** [stephenou/fruitionsite#5]
Are there plans to add a caching option for faster load times?

[Hosting Potion](https://www.hostingpotion.com/) seems to be doing this, would be awesome to have with furitionsite

**Comment by stephenou** [comment]
Good suggestion, but no plans yet, sorry. If performance is important to you, I think HostingPotion is the way to go. Different tools for different purposes.

If you're curious about the technical aspect, HostingPotion caches every page's DOM on their server, instead of loading from Notion on-demand. That means having your own server setup with storage space.

**Comment by Xalaxis** [comment]
Is it not possible to use the standard Cloudflare cache to cache images for example? I was having a look earlier today, but I couldn't figure out why they weren't being automatically cached.
